# Generated by Django 6.0.2 on 2026-02-27 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('ministry', models.CharField(blank=True, max_length=200)),
                ('target_stage', models.CharField(blank=True, max_length=100)),
                ('target_industry', models.CharField(blank=True, max_length=200)),
                ('max_funding', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=300)),
                ('eligibility_score', models.IntegerField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('partially', 'Partially Eligible'), ('not_eligible', 'Not Eligible'), ('applied', 'Applied'), ('tracking', 'Tracking')], default='eligible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schemes.governmentscheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-eligibility_score'],
            },
        ),
    ]
