# Generated by Django 6.0.2 on 2026-02-27 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='documents/')),
                ('ocr_text', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Passed'), ('fail', 'Failed'), ('review', 'Under Review')], default='pending', max_length=10)),
                ('report', models.TextField(blank=True)),
                ('issues_found', models.IntegerField(default=0)),
                ('suggestions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
