# Generated by Django 6.0.2 on 2026-02-27 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('financial_risk', models.IntegerField(blank=True, null=True)),
                ('market_risk', models.IntegerField(blank=True, null=True)),
                ('operational_risk', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('opportunities', models.TextField(blank=True)),
                ('threats', models.TextField(blank=True)),
                ('mitigation_suggestions', models.TextField(blank=True)),
                ('full_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
