# Generated by Django 6.0.2 on 2026-02-27 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP Stage'), ('early', 'Early Traction'), ('growth', 'Growth Stage')], default='idea', max_length=20)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('agri', 'Agriculture'), ('health', 'Healthcare'), ('edu', 'Education'), ('finance', 'FinTech'), ('retail', 'Retail/E-commerce'), ('logistics', 'Logistics'), ('other', 'Other')], default='tech', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
